/**
 * Key → lucide icon component for the venue's custom Lead Link buttons.
 *
 * Kept in its own module (separate from lead-link-icons.ts, which only holds
 * the plain key list used by the server-side sanitizer) so API routes don't
 * pull the whole icon set into their bundle. Must stay in sync with
 * LEAD_LINK_ICON_KEYS and the public renderer in the weddingdirectory repo.
 */
import {
  Link, Globe, Link2, ExternalLink, QrCode, Share2, Rss, Hash, Calendar,
  CalendarCheck, CalendarHeart, Clock, AlarmClock, Phone, Smartphone, Mail,
  MessageCircle, MessageSquare, Send, AtSign, Bell, Contact, Video, Play, Film,
  Clapperboard, Camera, Image, Images, Aperture, Focus, Music, Music2, Mic,
  Headphones, Disc, Radio, Speaker, Guitar, Piano, Star, Heart, HeartHandshake,
  ThumbsUp, Award, BadgeCheck, Trophy, Medal, Crown, Gem, Diamond, Sparkles,
  MapPin, Map, Navigation, Compass, Home, Building, Building2, Church, Landmark,
  Tent, TreePalm, Trees, Mountain, Waves, Sun, Sunset, Moon, Flower, Flower2,
  Leaf, Sprout, Utensils, UtensilsCrossed, ChefHat, Coffee, Wine, Martini, Beer,
  CupSoda, GlassWater, Cake, CakeSlice, Pizza, IceCream, Salad, Grape, Gift,
  PartyPopper, Ticket, Tickets, DollarSign, BadgeDollarSign, Tag, Tags,
  CreditCard, Wallet, Receipt, Percent, ShoppingBag, ShoppingCart, Store,
  Package, FileText, File, Book, BookOpen, Clipboard, ClipboardList, Newspaper,
  Info, List, ListChecks, Users, User, UserPlus, Handshake, Baby, Car, Plane,
  Bus, Ship, Anchor, Route, Armchair, BedDouble, Sofa, Lamp, Zap, Flame, Key,
  Palette, Paintbrush, Scissors, Feather, Snowflake, Umbrella, CheckCheck,
  type LucideIcon,
} from 'lucide-react';
import type { LeadLinkIconKey } from '@/lib/lead-link-icons';

export const LEAD_LINK_ICON_COMPONENTS: Record<LeadLinkIconKey, LucideIcon> = {
  'link': Link,
  'globe': Globe,
  'link-2': Link2,
  'external-link': ExternalLink,
  'qr-code': QrCode,
  'share-2': Share2,
  'rss': Rss,
  'hash': Hash,
  'calendar': Calendar,
  'calendar-check': CalendarCheck,
  'calendar-heart': CalendarHeart,
  'clock': Clock,
  'alarm-clock': AlarmClock,
  'phone': Phone,
  'smartphone': Smartphone,
  'mail': Mail,
  'message-circle': MessageCircle,
  'message-square': MessageSquare,
  'send': Send,
  'at-sign': AtSign,
  'bell': Bell,
  'contact': Contact,
  'video': Video,
  'play': Play,
  'film': Film,
  'clapperboard': Clapperboard,
  'camera': Camera,
  'image': Image,
  'images': Images,
  'aperture': Aperture,
  'focus': Focus,
  'music': Music,
  'music-2': Music2,
  'mic': Mic,
  'headphones': Headphones,
  'disc': Disc,
  'radio': Radio,
  'speaker': Speaker,
  'guitar': Guitar,
  'piano': Piano,
  'star': Star,
  'heart': Heart,
  'heart-handshake': HeartHandshake,
  'thumbs-up': ThumbsUp,
  'award': Award,
  'badge-check': BadgeCheck,
  'trophy': Trophy,
  'medal': Medal,
  'crown': Crown,
  'gem': Gem,
  'diamond': Diamond,
  'sparkles': Sparkles,
  'map-pin': MapPin,
  'map': Map,
  'navigation': Navigation,
  'compass': Compass,
  'home': Home,
  'building': Building,
  'building-2': Building2,
  'church': Church,
  'landmark': Landmark,
  'tent': Tent,
  'tree-palm': TreePalm,
  'trees': Trees,
  'mountain': Mountain,
  'waves': Waves,
  'sun': Sun,
  'sunset': Sunset,
  'moon': Moon,
  'flower': Flower,
  'flower-2': Flower2,
  'leaf': Leaf,
  'sprout': Sprout,
  'utensils': Utensils,
  'utensils-crossed': UtensilsCrossed,
  'chef-hat': ChefHat,
  'coffee': Coffee,
  'wine': Wine,
  'martini': Martini,
  'beer': Beer,
  'cup-soda': CupSoda,
  'glass-water': GlassWater,
  'cake': Cake,
  'cake-slice': CakeSlice,
  'pizza': Pizza,
  'ice-cream': IceCream,
  'salad': Salad,
  'grape': Grape,
  'gift': Gift,
  'party-popper': PartyPopper,
  'ticket': Ticket,
  'tickets': Tickets,
  'dollar-sign': DollarSign,
  'badge-dollar-sign': BadgeDollarSign,
  'tag': Tag,
  'tags': Tags,
  'credit-card': CreditCard,
  'wallet': Wallet,
  'receipt': Receipt,
  'percent': Percent,
  'shopping-bag': ShoppingBag,
  'shopping-cart': ShoppingCart,
  'store': Store,
  'package': Package,
  'file-text': FileText,
  'file': File,
  'book': Book,
  'book-open': BookOpen,
  'clipboard': Clipboard,
  'clipboard-list': ClipboardList,
  'newspaper': Newspaper,
  'info': Info,
  'list': List,
  'list-checks': ListChecks,
  'users': Users,
  'user': User,
  'user-plus': UserPlus,
  'handshake': Handshake,
  'baby': Baby,
  'car': Car,
  'plane': Plane,
  'bus': Bus,
  'ship': Ship,
  'anchor': Anchor,
  'route': Route,
  'armchair': Armchair,
  'bed-double': BedDouble,
  'sofa': Sofa,
  'lamp': Lamp,
  'zap': Zap,
  'flame': Flame,
  'key': Key,
  'palette': Palette,
  'paintbrush': Paintbrush,
  'scissors': Scissors,
  'feather': Feather,
  'snowflake': Snowflake,
  'umbrella': Umbrella,
  'check-check': CheckCheck,
};
