-- 173_venue_seo.sql
--
-- Automatic SEO fields for public venue listings. Generated by AI when the
-- listing goes live (test inquiry step) and regenerated when the owner edits
-- listing content. Never shown to the venue owner.

ALTER TABLE public.venues
  ADD COLUMN IF NOT EXISTS seo_title        text,
  ADD COLUMN IF NOT EXISTS seo_description  text,
  ADD COLUMN IF NOT EXISTS seo_keywords     text[],
  ADD COLUMN IF NOT EXISTS seo_generated_at timestamptz;

COMMENT ON COLUMN public.venues.seo_title IS
  'AI-generated meta title (~60 chars) for the public listing page. Auto-managed, not owner-editable.';
COMMENT ON COLUMN public.venues.seo_description IS
  'AI-generated meta description (~155 chars) for the public listing page. Auto-managed.';
COMMENT ON COLUMN public.venues.seo_keywords IS
  'AI-generated target keywords for the listing. Used in meta keywords and internal linking.';

NOTIFY pgrst, 'reload schema';
